name: 'tw5-plugin-packer'
author: 'Gk0Wk'
description: 'Pack up your TiddlyWiki5 plugin folders to JSON files.'
inputs:
  source:
    description: 'The root directory of your plugin. You can add multiple paths in the form of one per line.'
    required: true
  output:
    description: 'The output path of the packed plugin files, default to "output".'
    required: false
    default: 'output'
outputs:
  output-plugins:
    description: 'The JSON file path of the successfully exported plugin, stored as an array of strings in JSON format.'
runs:
  using: 'node16'
  main: 'packup.js'
